services:
  school_management:
    build: .
    depends_on:
      - db
#      db:
#          condition: service_healthy
#      healthcheck:
#        test: ["CMD", "curl", "-f", "http://localhost:8080"]
#        interval: 60s
#        timeout: 10s
#        retries: 3
#        start_period: 30s
    working_dir: /SchoolManagement
    env_file:
      - .env
    environment:
      - PG_DATABASE_ADDRESS=db
    ports:
      - "8000:8080"
    networks:
      - front-tier
      - back-tier

  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "sm-db-data:/var/lib/postgresql/data"
#      - "./healthchecks:/healthchecks"
      - "./docker_postgres_init.sh:/docker-entrypoint-initdb.d/docker_postgres_init.sh"
    #    healthcheck:
    #      test: /healthchecks/postgres.sh
    #      interval: "10s"
    networks:
      - back-tier

  # this service runs once to create database tables
  # it won't run unless you specify the "seed" profile
  # docker compose --profile seed up -d
#  seed:
#    build: ./seed-data
#    profiles: ["seed"]
#    depends_on:
#      vote:
#        condition: service_healthy
#    networks:
#      - front-tier
#    restart: "no"


volumes:
  sm-db-data:

networks:
  front-tier:
  back-tier: