services:
  web:
    build: .
    image: leechlab/school-management:latest
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:80 || exit 1
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
    working_dir: /School-management
    env_file:
      - .env
    environment:
      - PG_DATABASE_ADDRESS=db
      - IS_DOCKER=true
      - FILL_DATABASE=${FILL_DATABASE}
    ports:
      - "80:80"
    networks:
      - front-tier
      - back-tier
    restart: "always"

  db:
    build: postgres
    image:  leechlab/sm_postgres_db:latest
    env_file:
      - .env
    volumes:
      - "db-data:/var/lib/postgresql/data"
    healthcheck:
      test: bash /healthchecks/postgres.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - back-tier
    restart: "always"

volumes:
  db-data:

networks:
  front-tier:
  back-tier: