version: '3'

services:
  web:
    build: .
    image: leechlab/school-management:latest
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:80 || exit 1
      interval: 60s
      timeout: 10s
      retries: 3
    working_dir: /School-management
    env_file:
      - .env
    environment:
      - PG_DATABASE_ADDRESS=db
      - IS_DOCKER=true
    ports:
      - "8081:80"
    networks:
      front-tier:
      back-tier:

  db:
    build: postgres
    image:  leechlab/sm_postgres_db:latest
    env_file:
      - .env
    volumes:
      - "db-data:/var/lib/postgresql/data"
    healthcheck:
      test: bash /healthchecks/postgres.sh
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - back-tier

  # this service runs once to fill the database with random data
  # it won't run unless you specify the "fill" profile
  # docker compose --profile fill up -d
  fill:
    image: leechlab/school-management:latest
    profiles: ["fill"]
    working_dir: /School-management
    env_file:
      - .env
    environment:
      - PG_DATABASE_ADDRESS=db
      - IS_DOCKER=true
    command: python ./src/fill_database.py
    depends_on:
      web:
        condition: service_healthy
    networks:
      - back-tier
    restart: "no"

volumes:
  db-data:

networks:
  front-tier:
  back-tier: