services:
  web:
    build: .
    command: python3 ./src/create_tables.py; FLASK_APP="src/school_management/run.py" flask run --host 0.0.0.0 --port=8080
    depends_on:
      db:
          condition: service_healthy
#      healthcheck:
#        test: curl -f https://localhost || exit 1
#        interval: 60s
#        timeout: 10s
#        retries: 3
#        start_period: 60s
    working_dir: /SchoolManagement
    env_file:
      - .env
    environment:
      - PG_DATABASE_ADDRESS=db
      - IS_DOCKER=true
    ports:
      - "8000:8080"
    networks:
      - front-tier
      - back-tier

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
      - "./docker_postgres_init.sh:/docker-entrypoint-initdb.d/docker_postgres_init.sh"
    healthcheck:
      test: bash ./healthchecks/postgres.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - back-tier

  # this service runs once to create database tables
  # it won't run unless you specify the "seed" profile
  # docker compose --profile seed up -d
#  seed:
#    build: ./seed-data
#    profiles: ["seed"]
#    depends_on:
#      vote:
#        condition: service_healthy
#    networks:
#      - front-tier
#    restart: "no"


volumes:
  db-data:

networks:
  front-tier:
  back-tier: